# Generated by Django 4.2.7 on 2025-09-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0005_alter_qrcode_prize_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBoxHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prize_type', models.CharField(max_length=50)),
                ('prize_value', models.IntegerField(default=0)),
                ('prize_description', models.TextField(max_length=200)),
                ('is_special_prize', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_codes.qrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_box_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mystery Box History',
                'verbose_name_plural': 'Mystery Box Histories',
                'ordering': ['-opened_at'],
            },
        ),
    ]
