# Generated by Django 4.2.7 on 2025-11-06 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(help_text='Format MP4 recommandé, max 50MB', upload_to='advertisements/videos/', verbose_name='Fichier vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='advertisements/thumbnails/', verbose_name='Miniature')),
                ('duration', models.IntegerField(default=5, help_text="Temps d'affichage avant de passer à la suivante", verbose_name="Durée d'affichage (secondes)")),
                ('priority', models.IntegerField(default=0, help_text="Plus le nombre est élevé, plus la vidéo a de chances d'être affichée", verbose_name='Priorité')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Programmée')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(blank=True, help_text='Laisser vide pour démarrer immédiatement', null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, help_text='Laisser vide pour pas de limite', null=True, verbose_name='Date de fin')),
                ('views_count', models.IntegerField(default=0, verbose_name="Nombre d'affichages")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Vidéo Publicitaire',
                'verbose_name_plural': 'Vidéos Publicitaires',
                'db_table': 'video_advertisements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
