# Generated by Django 4.2.7 on 2025-11-18 14:01

from django.db import migrations, models
import uuid


def create_default_banner(apps, schema_editor):
    HomeBanner = apps.get_model('dashboard', 'HomeBanner')
    if not HomeBanner.objects.exists():
        HomeBanner.objects.create(
            title="Aya+",
            subtitle="Fidélisez vos clients avec Aya+",
            button_text="Decouvrir Aya+",
            button_url="https://example.com",
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_videoadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/banners/', verbose_name='Image')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Texte du bouton')),
                ('button_url', models.URLField(blank=True, verbose_name='Lien du bouton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bannière d'accueil",
                'verbose_name_plural': "Bannières d'accueil",
                'db_table': 'home_banners',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(create_default_banner, migrations.RunPython.noop),
    ]
