# Generated by Django 5.2.6 on 2025-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, help_text='Ville', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default="Côte d'Ivoire", help_text='Pays', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='region',
            field=models.CharField(blank=True, help_text='Région', max_length=100),
        ),
    ]
