# Generated by Django 4.2.7 on 2025-09-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_vendor_city_vendor_country_vendor_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du grand prix')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('draw_date', models.DateTimeField(verbose_name='Date de tirage au sort')),
                ('participation_cost', models.IntegerField(default=100, verbose_name='Coût de participation (points)')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('active', 'En cours'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grand_prizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grand Prix',
                'verbose_name_plural': 'Grands Prix',
                'db_table': 'grand_prizes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GrandPrixPrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(choices=[(1, '1er prix'), (2, '2ème prix'), (3, '3ème prix'), (4, '4ème prix'), (5, '5ème prix')], verbose_name='Position')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la récompense')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur (€)')),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='authentication.grandprix')),
            ],
            options={
                'verbose_name': 'Récompense Grand Prix',
                'verbose_name_plural': 'Récompenses Grand Prix',
                'db_table': 'grand_prize_prizes',
                'ordering': ['position'],
                'unique_together': {('grand_prix', 'position')},
            },
        ),
        migrations.CreateModel(
            name='GrandPrixParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.IntegerField(verbose_name='Points dépensés')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Gagnant')),
                ('participated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de participation')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='authentication.grandprix')),
                ('prize_won', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='authentication.grandprixprize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_prix_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation Grand Prix',
                'verbose_name_plural': 'Participations Grand Prix',
                'db_table': 'grand_prize_participations',
                'ordering': ['-participated_at'],
                'unique_together': {('grand_prix', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GrandPrixDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drawn_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du tirage')),
                ('drawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_draws', to=settings.AUTH_USER_MODEL)),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='authentication.grandprix')),
                ('winners', models.ManyToManyField(blank=True, related_name='draw_wins', to='authentication.grandprixparticipation')),
            ],
            options={
                'verbose_name': 'Tirage Grand Prix',
                'verbose_name_plural': 'Tirages Grand Prix',
                'db_table': 'grand_prize_draws',
                'ordering': ['-drawn_at'],
            },
        ),
    ]
