# Generated by Django 4.2.7 on 2025-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_location_fields'),
        ('authentication', '0005_grandprix_grandprixprize_grandprixparticipation_and_more'),
    ]

    operations = [
    ]
