# Generated by Django 5.2.6 on 2025-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='prize_type',
            field=models.CharField(choices=[('points', 'Points'), ('loyalty_ticket', 'Ticket de Fidélité'), ('special_prize', 'Prix Spécial')], default='points', max_length=20),
        ),
    ]
