# Generated by Django 5.2.6 on 2025-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0003_exchangetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Numéro de lot (ex: 4151000)', max_length=50),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='batch_sequence',
            field=models.IntegerField(blank=True, help_text='Numéro de séquence dans le lot', null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='QR code imprimé sur bouteille'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='prize_type',
            field=models.CharField(choices=[('points', 'Points'), ('loyalty_ticket', 'Ticket de Fidélité'), ('special_prize', 'Prix Spécial'), ('try_again', 'Réessayer'), ('scratch_win', 'Scratch & Win'), ('mystery_box', 'Boîte Mystère'), ('loyalty_bonus', 'Bonus Fidélité')], default='points', max_length=20),
        ),
    ]
