# Generated by Django 4.2.7 on 2025-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0004_qrcode_batch_number_qrcode_batch_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='prize_type',
            field=models.CharField(choices=[('points', 'Points'), ('try_again', 'Réessayer'), ('loyalty_bonus', 'Bonus Fidélité'), ('mystery_box', 'Boîte Mystère')], default='points', max_length=20),
        ),
    ]
