# Generated by Django 4.2.7 on 2025-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0005_alter_qrcode_prize_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetoken',
            name='points_restored',
            field=models.BooleanField(default=False),
        ),
    ]
