# Generated by Django 4.2.7 on 2025-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0006_exchangetoken_points_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='category',
            field=models.CharField(choices=[('1.5L', 'Bouteille 1.5 L'), ('5L', 'Bouteille 5 L'), ('bedon', 'Bedon')], default='1.5L', help_text='Catégorie de la bouteille', max_length=20),
        ),
    ]
